using Repository_Lab_Application.Interfaces.RepositoryInterfaces;
using Repository_Lab_Application.Interfaces.RepositoryInterfaces.Read;
using Repository_Lab_Application.Interfaces.Service_Interfaces;
using Repository_Lab_Core.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace Repository_Lab_Application.Services
{
    public class AuctionService : IAuctionService
    {
        private readonly IReadAuctionRepository _readAuctionRepository;
        private readonly IUnitOfWork _unitOfWork;
        public AuctionService(IReadAuctionRepository readAuctionRepository, IUnitOfWork unitOfWork)
        {
            _readAuctionRepository = readAuctionRepository; 
            _unitOfWork = unitOfWork;

        }
        public async Task PliceBidAsync(int auctionId, decimal amount, CancellationToken cancellationToken)
        {
            var auction = await _readAuctionRepository.GetByIdAsync(auctionId, cancellationToken);
            if (auction == null)
            {
                throw new Exception("Auction not found");
            }
            if (auction.EndDate < DateTime.UtcNow)
            {
                throw new Exception("Auction has ended");
            }

            var bid = new Bid
            {
                Amount = amount,
                AuctionId = auctionId,
                Id = 1 // assume the id is generated by the database
            };

            auction.Bids.Add(bid);
            await _unitOfWork.SaveChangesAsync(cancellationToken);
            
        }
    }
}
